name: Pipeline RecargaYa

on:
  push:
    branches: [ "main" ]

jobs:
  pruebas-automatizadas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: false
    - run: uv sync --all-extras --dev

    - name: Pruebas Unitarias y Comportamiento (TDD/BDD)
      run: uv run pytest tests/ --cov=src --cov-fail-under=85

    - name: Pruebas de Rendimiento Estricto (P95)
      run: |

        uv run uvicorn src.api:app --host 127.0.0.1 --port 8000 &
        sleep 3 # Esperamos 3 segundos a que la API prenda bien
     
        uv run locust -f tests/performance/locustfile.py --headless -u 30 -r 10 --run-time 15s --host http://127.0.0.1:8000